## Customer list data clean up

In [2]:
import pandas as pd

df = pd.read_csv("customer_list_updated.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    object
dtypes: object(1)
memory usage: 4.2+ KB

#### see how the data us displaying

In [4]:
df.head()

     cust_id|date|time|name|email|phone|sms-opt-out
0  1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1  2|2023-05-22|12:30:45|R&! Geller|rossg@central...
2  3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3  4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4  5|2023-11-18|14:22:10|Joey|howyoudoing@central...

In [5]:
df.drop_duplicates()

       cust_id|date|time|name|email|phone|sms-opt-out
0    1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1    2|2023-05-22|12:30:45|R&! Geller|rossg@central...
2    3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3    4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4    5|2023-11-18|14:22:10|Joey|howyoudoing@central...
..                                                 ...
516  517|2024-02-15|11:30:30|Perry the Platypus|age...
517  518|2024-05-01|15:55:45|Baljeet|baljeet@danvil...
518  519|2023-03-05|09:20:00|Buford|buford@danville...
519  520|2023-05-18|13:45:15|Vanessa D.^|vanessa@da...
520  521|2023-08-01|18:10:30|Linda Flynn-Fletcher|l...

[521 rows x 1 columns]

#### The  delimiter = '|' seprates the code

In [36]:
upper_list = pd.read_csv('customer_list_updated.csv', delimiter = '|')
columns = ('cust_id', 'date', 'time', 'name', 'email', 'phone', 'sms-opt-out')

In [7]:
upper_list

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R&! Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N
...,...,...,...,...,...,...,...
516,517,2024-02-15,11:30:30,Perry the Platypus,agentp@danvillekids.com,555-555-3206,N
517,518,2024-05-01,15:55:45,Baljeet,baljeet@danvillekids.com,555-555-3207,N
518,519,2023-03-05,09:20:00,Buford,buford@danvillekids.com,555-555-3208,N
519,520,2023-05-18,13:45:15,Vanessa D.^,vanessa@danvillekids.com,555-555-3209,N
520,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N

#### Convert the value to a string to use replace and replace the special charecters

In [8]:
for i in upper_list['name']: 
    # Convert the value to a string to use replace
     name = str(['name'])  
    #the code below is getting rid of the extra charecters
     if '&' in name:
         upper_list.at[i, 'name'] = name.replace('&','')  
     elif '^' in name:
         upper_list.at[i, 'name'] = name.replace('^','')  
     elif '.' in name:
         upper_list.at[i, 'name'] = name.replace('.','')  
     elif '-' in name:
         upper_list.at[i, 'name'] = name.replace('-','') 
     elif '!' in name:
         upper_list.at[i, 'name'] = name.replace('!','')

In [9]:
upper_list

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R&! Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N
...,...,...,...,...,...,...,...
516,517,2024-02-15,11:30:30,Perry the Platypus,agentp@danvillekids.com,555-555-3206,N
517,518,2024-05-01,15:55:45,Baljeet,baljeet@danvillekids.com,555-555-3207,N
518,519,2023-03-05,09:20:00,Buford,buford@danvillekids.com,555-555-3208,N
519,520,2023-05-18,13:45:15,Vanessa D.^,vanessa@danvillekids.com,555-555-3209,N
520,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N

#### cleaning sms

In [59]:
upper_list = upper_list.rename(columns = { 'sms-opt-out ' : 'sms-opt-out' })

In [60]:
upper_list

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R&! Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N
...,...,...,...,...,...,...,...
516,517,2024-02-15,11:30:30,Perry the Platypus,agentp@danvillekids.com,555-555-3206,N
517,518,2024-05-01,15:55:45,Baljeet,baljeet@danvillekids.com,555-555-3207,N
518,519,2023-03-05,09:20:00,Buford,buford@danvillekids.com,555-555-3208,N
519,520,2023-05-18,13:45:15,Vanessa D.^,vanessa@danvillekids.com,555-555-3209,N
520,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N